services:
  - type: web
    name: seal-web-app
    runtime: node
    buildCommand: pip install yt-dlp && npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
